package kirjastoSWING;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
//import kirjastoSWING.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.06.17 17:28:05 // Generated by ComTest
 *
 */
public class LainaajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa21 
 * @throws SailoException */
  @Test
  public void testLisaa21() throws SailoException {    // Lainaajat: 21
    Lainaajat lainuri = new Lainaajat(); 
    Lainaaja erkki = new Lainaaja(); 
    Lainaaja martta = new Lainaaja(); 
    erkki.vastaaLainaaja(); 
    martta.vastaaLainaaja(); 
    lainuri.lisaa(erkki); 
    assertEquals("From: Lainaajat line: 28", 1, lainuri.getLkm()); 
    lainuri.lisaa(martta); 
    assertEquals("From: Lainaajat line: 30", 2, lainuri.getLkm()); 
    assertEquals("From: Lainaajat line: 31", erkki, lainuri.anna(0)); 
    assertEquals("From: Lainaajat line: 32", martta, lainuri.anna(1)); 
  } // Generated by ComTest END
}